# Generated by Django 5.2.4 on 2025-09-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='response_time',
            field=models.CharField(blank=True, default='Usually responds within 24 hours', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='return_policy',
            field=models.TextField(blank=True, default='30-day return policy'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shipping_policy',
            field=models.TextField(blank=True, default='Standard shipping rates apply'),
        ),
    ]
