# Generated by Django 5.2.4 on 2025-09-22 13:43

from django.db import migrations
from django.utils.text import slugify


def create_default_categories(apps, schema_editor):
    """Create default product categories"""
    category_model = apps.get_model('products', 'Category')
    
    categories = [
        {
            'name': 'Electronics',
            'description': 'Computers, phones, tablets, accessories and electronic gadgets'
        },
        {
            'name': 'Clothing & Fashion',
            'description': 'Men\'s, women\'s and children\'s clothing, shoes and accessories'
        },
        {
            'name': 'Home & Garden',
            'description': 'Furniture, home decor, garden tools and household items'
        },
        {
            'name': 'Sports & Outdoors',
            'description': 'Exercise equipment, outdoor gear, sporting goods'
        },
        {
            'name': 'Books & Media',
            'description': 'Books, movies, music, games and educational materials'
        },
        {
            'name': 'Health & Beauty',
            'description': 'Skincare, makeup, health supplements and wellness products'
        },
        {
            'name': 'Automotive',
            'description': 'Car parts, accessories, tools and automotive supplies'
        },
        {
            'name': 'Toys & Games',
            'description': 'Children\'s toys, board games, puzzles and educational toys'
        },
        {
            'name': 'Jewelry & Watches',
            'description': 'Fine jewelry, fashion jewelry, watches and accessories'
        },
        {
            'name': 'Food & Beverages',
            'description': 'Gourmet foods, beverages, snacks and cooking ingredients'
        },
        {
            'name': 'Art & Crafts',
            'description': 'Art supplies, craft materials, handmade items and collectibles'
        },
        {
            'name': 'Office Supplies',
            'description': 'Office equipment, stationery, business supplies and furniture'
        }
    ]

    for category_data in categories:
        category_model.objects.get_or_create(
            name=category_data['name'],
            defaults={
                'slug': slugify(category_data['name']),
                'description': category_data['description'],
                'is_active': True
            }
        )


def reverse_create_default_categories(apps, schema_editor):
    """Remove default categories (for rollback)"""
    category_model = apps.get_model('products', 'Category')
    
    default_category_names = [
        'Electronics', 'Clothing & Fashion', 'Home & Garden', 'Sports & Outdoors',
        'Books & Media', 'Health & Beauty', 'Automotive', 'Toys & Games',
        'Jewelry & Watches', 'Food & Beverages', 'Art & Crafts', 'Office Supplies'
    ]
    
    category_model.objects.filter(name__in=default_category_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_create_default_categories),
    ]
